services:
  - type: web
    name: eduops360
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: DATABASE_URL
        value: sqlite:///GGU_DBA_ET_Learner_Journey.db
      - key: SESSION_TIMEOUT_HOURS
        value: 24
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
